name: Build JOSS Manuscript

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  paper:
    name: Generate JOSS PDF Draft
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build JOSS Draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md

      - name: Upload Manuscript PDF
        uses: actions/upload-artifact@v4
        with:
          name: joss-paper
          path: paper/paper.pdf
